local UILib = loadstring(game:HttpGet("https://raw.githubusercontent.com/saintdevzz/saint-ui/main/UILIB.lua?v=" .. os.time()))()
local window = UILib:Window({ name = "VapeUI" })
window:Page("Combat")
window:Page("Render")
window:Page("Utility")
window:Page("World")
window:Page("Inventory")
window:Page("Minigames")
window:Page("Other")
window:Page({ title = "Friends", misc = true })
window:Page({ title = "Profiles", misc = true, tag = "default" })
window:Page({ title = "Macros", misc = true })
local combat = window.pages["Combat"]
local aim = combat:Module({ title = "AimAssist", callback = function(v) print(v) end })
aim:Toggle({ title = "Enabled", value = true, callback = function(v) print(v) end })
aim:Slider({ title = "FOV", min = 0, max = 360, value = 90 })
combat:Module("AutoClicker")
combat:Module("BlockHit")
combat:Module("HitSelect")
combat:Module("Reach")
combat:Module("RightClicker")
combat:Module("SilentAura")
combat:Module("Sprint")
combat:Module("Velocity")
combat:Module("WTap")
local render = window.pages["Render"]
local esp = render:Module("ESP")
local box = esp:Panel("Box ESP")
box:Toggle({ title = "Enabled", value = true })
box:Slider({ title = "Thickness", min = 1, max = 5, value = 2 })
local bones = esp:Panel("Skeleton ESP")
bones:Toggle({ title = "Enabled", value = false })
bones:Dropdown({ title = "Style", options = { "Lines", "Dots" }, default = "Lines" })
render:Module("Chams")
window.pages["Utility"]:Module("Blink")
window:Select("Combat")
window:Select("Render")
