local UILib = loadstring(game:HttpGet("https://raw.githubusercontent.com/saintdevzz/saint-ui/main/UILIB.lua?v=" .. os.time()))()
local window = UILib:Window({ name = "MIGUEL" })
window:Page("Combat")
window:Page("Render")
window:Page("Utility")
window:Page("World")
window:Page("Inventory")
window:Page("Minigames")
window:Page("Other")
window:Page({ title = "Friends", misc = true })
window:Page({ title = "Profiles", misc = true, tag = "default" })
window:Page({ title = "Macros", misc = true })
local combat = window.pages["Combat"]
local aimbot = combat:Module({ title = "Aimbot" })
aimbot:Toggle({ title = "Enabled", value = true, callback = function(v) print("[MIGUEL] Aimbot", v) end })
aimbot:Slider({ title = "FOV", min = 0, max = 360, value = 90, callback = function(v) print("[MIGUEL] FOV", v) end })
aimbot:Slider({ title = "Smoothness", min = 1, max = 100, value = 35, callback = function(v) print("[MIGUEL] Smooth", v) end })
aimbot:Dropdown({ title = "Target", options = { "Head", "Torso", "Closest", "Lowest HP" }, default = "Head", callback = function(v) print("[MIGUEL] Target", v) end })
aimbot:Toggle({ title = "Visible only", value = true })
aimbot:Keybind({ title = "Bind", key = Enum.KeyCode.Q, callback = function(k) print("[MIGUEL] Bind", k and k.Name) end })
local clicker = combat:Module("AutoClicker")
clicker:Toggle({ title = "Enabled", value = false, callback = function(v) print("[MIGUEL] Clicker", v) end })
clicker:Slider({ title = "CPS", min = 1, max = 20, value = 12, callback = function(v) print("[MIGUEL] CPS", v) end })
clicker:Dropdown({ title = "Mode", options = { "Toggle", "Hold" }, default = "Toggle" })
local reach = combat:Module("Reach")
reach:Toggle({ title = "Enabled", value = true })
reach:Slider({ title = "Distance", min = 3, max = 7, value = 4, decimals = 1, callback = function(v) print("[MIGUEL] Reach", v) end })
local hit = combat:Module("HitSelect")
hit:Toggle({ title = "Enabled", value = false })
hit:Slider({ title = "Chance", min = 0, max = 100, value = 50, suffix = "%" })
local sprint = combat:Module("Sprint")
sprint:Toggle({ title = "Enabled", value = true })
sprint:Keybind({ title = "Key", key = Enum.KeyCode.W })
local velo = combat:Module("Velocity")
local vset = velo:Panel("Velocity Settings")
vset:Toggle({ title = "Enabled", value = true })
vset:Slider({ title = "Horizontal", min = 0, max = 100, value = 100, callback = function(v) print("[MIGUEL] H", v) end })
vset:Slider({ title = "Vertical", min = 0, max = 100, value = 100, callback = function(v) print("[MIGUEL] V", v) end })
vset:Dropdown({ title = "Mode", options = { "Normal", "Ground", "Air" }, default = "Normal" })
combat:Module("BlockHit")
combat:Module("SilentAura")
combat:Module("WTap")
combat:Module("RightClicker")
local render = window.pages["Render"]
local esp = render:Module("ESP")
local box = esp:Panel("Box ESP")
box:Toggle({ title = "Enabled", value = true, callback = function(v) print("[MIGUEL] Box", v) end })
box:Slider({ title = "Thickness", min = 1, max = 5, value = 2 })
box:Dropdown({ title = "Color", options = { "White", "Red", "Blue", "Green" }, default = "White" })
local skele = esp:Panel("Skeleton ESP")
skele:Toggle({ title = "Enabled", value = false })
skele:Slider({ title = "Transparency", min = 0, max = 100, value = 0 })
skele:Dropdown({ title = "Style", options = { "Lines", "Dots" }, default = "Lines" })
local name = esp:Panel("Name ESP")
name:Toggle({ title = "Enabled", value = true })
name:Slider({ title = "Text size", min = 10, max = 24, value = 14 })
local tracer = esp:Panel("Tracer ESP")
tracer:Toggle({ title = "Enabled", value = false })
tracer:Slider({ title = "Thickness", min = 1, max = 5, value = 1 })
local chams = render:Module("Chams")
chams:Toggle({ title = "Enabled", value = false, callback = function(v) print("[MIGUEL] Chams", v) end })
chams:Dropdown({ title = "Material", options = { "Flat", "Neon", "ForceField" }, default = "Flat" })
local fullbright = render:Module("Fullbright")
fullbright:Toggle({ title = "Enabled", value = true })
fullbright:Slider({ title = "Brightness", min = 1, max = 10, value = 3 })
local camera = render:Module("Camera")
camera:Slider({ title = "FOV", min = 70, max = 120, value = 90, callback = function(v) print("[MIGUEL] Cam FOV", v) end })
camera:Toggle({ title = "No shake", value = true })
local utility = window.pages["Utility"]
local blink = utility:Module("Blink")
blink:Toggle({ title = "Enabled", value = false })
blink:Keybind({ title = "Key", key = Enum.KeyCode.B })
local timer = utility:Module("Timer")
timer:Slider({ title = "Speed", min = 1, max = 10, value = 2, decimals = 1 })
local fastplace = utility:Module("FastPlace")
fastplace:Toggle({ title = "Enabled", value = true })
local world = window.pages["World"]
local timeChanger = world:Module("TimeChanger")
timeChanger:Slider({ title = "Hour", min = 0, max = 24, value = 14, callback = function(v) print("[MIGUEL] Hour", v) end })
timeChanger:Toggle({ title = "Freeze", value = false })
local sky = world:Module("Skybox")
sky:Dropdown({ title = "Preset", options = { "Default", "Night", "Sunset", "Space" }, default = "Default" })
local fog = world:Module("Fog")
fog:Toggle({ title = "Enabled", value = false })
fog:Slider({ title = "Density", min = 0, max = 100, value = 30 })
local inventory = window.pages["Inventory"]
local stealer = inventory:Module("ChestStealer")
stealer:Toggle({ title = "Enabled", value = false, callback = function(v) print("[MIGUEL] Stealer", v) end })
stealer:Slider({ title = "Delay", min = 0, max = 500, value = 50, suffix = "ms" })
local instant = inventory:Module("InstantEquip")
instant:Toggle({ title = "Enabled", value = true })
local minigames = window.pages["Minigames"]
local bed = minigames:Module("BedNuker")
bed:Toggle({ title = "Enabled", value = false })
bed:Slider({ title = "Radius", min = 1, max = 10, value = 5 })
local scaffold = minigames:Module("Scaffold")
scaffold:Toggle({ title = "Enabled", value = false })
scaffold:Keybind({ title = "Key", key = Enum.KeyCode.V })
local other = window.pages["Other"]
local ac = other:Module("AnticheatDisabler")
ac:Dropdown({ title = "Method", options = { "Basic", "Advanced", "Custom" }, default = "Basic", callback = function(v) print("[MIGUEL] AC", v) end })
ac:Toggle({ title = "Auto rejoin", value = false })
local anti = other:Module("AntiVoid")
anti:Toggle({ title = "Enabled", value = true })
local friend = window.pages["Friends"]:Module("Friend ESP")
friend:Toggle({ title = "Enabled", value = true })
friend:Dropdown({ title = "Highlight", options = { "Box", "Name", "Both" }, default = "Both" })
local prof = window.pages["Profiles"]:Module("Profile Manager")
prof:Dropdown({ title = "Config", options = { "default", "pvp", "legit", "rage" }, default = "default", callback = function(v) print("[MIGUEL] Config", v) end })
prof:Button({ title = "Save", button = "Save", callback = function() print("[MIGUEL] saved") end })
prof:Button({ title = "Load", button = "Load", callback = function() print("[MIGUEL] loaded") end })
local macros = window.pages["Macros"]:Module("Macro Runner")
macros:Dropdown({ title = "Macro", options = { "Combo", "Flick", "Pot" }, default = "Combo" })
macros:Button({ title = "Run macro", button = "Run", callback = function() print("[MIGUEL] macro run") end })
window:Select("Combat")
window:Select("Render")
print("[MIGUEL] loaded build 7")
